### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by paternal** [texfaq/historical#1]
The website https://www.tex.ac.uk/ is unreachable (I get a github 404 page). This looks like a error in the github pages configuration.

I am not sure how relevant this is, since this repo is marked as `historical`, but since it is still referenced on the internet ([example](https://en.wikipedia.org/wiki/LuaTeX#cite_ref-3)), it would be nice to keep it live.

Cross posted in uktug/uk-tex-faq#7, since I cannot figure which is the "official" repository.

-- Louis

**Comment by josephwright** [comment]
Duplicate of https://github.com/uktug/uk-tex-faq/issues/7

**Comment by josephwright** [comment]
Duplicate of https://github.com/uktug/uk-tex-faq/issues/7

**Comment by josephwright** [comment]
Oops, wrong repo duped to: I thought you'd reported again the live data.

**Comment by josephwright** [comment]
This is now fixed :)
